# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azpim < Formula
  desc "CLI for managing Azure Privileged Identity Management (PIM) role assignments"
  homepage "https://github.com/bgs113/azpim"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bgs113/azpim/releases/download/v1.1.1/azpim-v1.1.1-darwin-amd64.zip"
      sha256 "f84688edfe85aa3adfc20711bbad2a6a6b2d40c87dd738180526de7f5c795f7c"

      define_method(:install) do
        bin.install "azpim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bgs113/azpim/releases/download/v1.1.1/azpim-v1.1.1-darwin-arm64.zip"
      sha256 "278f4f5da6b52da261b82e2a10bd0aa9d2e62faed6483011de9869cee11e742d"

      define_method(:install) do
        bin.install "azpim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bgs113/azpim/releases/download/v1.1.1/azpim-v1.1.1-linux-amd64.zip"
      sha256 "c37b99f51db9c3cf83a1b59666d5f3c883982ab3639e964b6e2b319c70fdd92f"
      define_method(:install) do
        bin.install "azpim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bgs113/azpim/releases/download/v1.1.1/azpim-v1.1.1-linux-arm64.zip"
      sha256 "a3de36b9126ec3cac410f8cbb2eaccb4c365a58e28c9986097d3b477736aae18"
      define_method(:install) do
        bin.install "azpim"
      end
    end
  end

  test do
    system bin/"azpim", "version"
  end
end
