# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azpim < Formula
  desc "CLI for managing Azure Privileged Identity Management (PIM) role assignments"
  homepage "https://github.com/bgs113/azpim"
  version "1.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bgs113/azpim/releases/download/v1.2.3/azpim-v1.2.3-darwin-amd64.zip"
      sha256 "9266777366dd061c04e96830d3872fcf36fb4fcd239b93815c5b0db3a51a3b60"

      define_method(:install) do
        bin.install "azpim"
        generate_completions_from_executable(bin/"azpim", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bgs113/azpim/releases/download/v1.2.3/azpim-v1.2.3-darwin-arm64.zip"
      sha256 "78a89572dc44d821c28411e152ae7acbbcb6c58cfe35ed61a598cf0736185229"

      define_method(:install) do
        bin.install "azpim"
        generate_completions_from_executable(bin/"azpim", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bgs113/azpim/releases/download/v1.2.3/azpim-v1.2.3-linux-amd64.zip"
      sha256 "aeab71990cfaa3b631ca4dfbc97920441c2d4317455d79cbff1505ee83e979c7"
      define_method(:install) do
        bin.install "azpim"
        generate_completions_from_executable(bin/"azpim", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bgs113/azpim/releases/download/v1.2.3/azpim-v1.2.3-linux-arm64.zip"
      sha256 "7f31689cc25a63b550b062d496db6a78b5fb8ad820d1cf29cd42a8de9ea62eb8"
      define_method(:install) do
        bin.install "azpim"
        generate_completions_from_executable(bin/"azpim", "completion")
      end
    end
  end

  test do
    assert_match "azpim #{version}", shell_output("#{bin}/azpim --version")
  end
end
