# This file was generated by GoReleaser. DO NOT EDIT.
cask "azpim" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "1bc96b209615d03aeea1660a08490b25e81276ed42329ffa40c6e79a652aa17b"
      url "https://github.com/bgs113/azpim/releases/download/v#{version}/azpim-v#{version}-darwin-amd64.zip"
    end
    on_arm do
      sha256 "ee7a9885849965db9a060521637de4965dc17830d7747f8d00c7f6e15b8499ec"
      url "https://github.com/bgs113/azpim/releases/download/v#{version}/azpim-v#{version}-darwin-arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a79b8052ff0193333aa579bc1b1f62de3adab6d07197b139eae18dced01d11e"
      url "https://github.com/bgs113/azpim/releases/download/v#{version}/azpim-v#{version}-linux-amd64.zip"
    end
    on_arm do
      sha256 "a83b332350cf4f606009d29439b86c252535a460130f279df6e8fc1104525ee8"
      url "https://github.com/bgs113/azpim/releases/download/v#{version}/azpim-v#{version}-linux-arm64.zip"
    end
  end

  name "azpim"
  desc "CLI for managing Azure Privileged Identity Management (PIM) role assignments"
  homepage "https://github.com/bgs113/azpim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "azpim"

  # No zap stanza required

end
